# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-116935518-1'

menu:
- {name: 'Research', folder: 'pages', file: 'research.html'}
- {name: 'Publications', folder: 'pages', file: 'publications.html'}
- {name: 'People', folder: 'pages', file: 'people.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/zapata_lab'}
- {icon: 'envelope', link: 'mailto:zapatalab@gmail.com'}
- {icon: 'slack', link: 'https://zapatalab.slack.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
#pagination:
#  next_page: 'Newer'
#  previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

#related_posts: 'Learn more about the lab...'

#post_date_prefix: 'Written on'
